//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautyHome.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment_product
    {
        public long comment_puduct_id { get; set; }
        public Nullable<long> product_id { get; set; }
        public Nullable<long> user_id { get; set; }
        public string txt_comment { get; set; }
    
        public virtual product product { get; set; }
    }
}
