//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautyHome.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.comment_product = new HashSet<comment_product>();
            this.orders = new HashSet<order>();
        }
    
        public long product_id { get; set; }
        public Nullable<long> type_product_id { get; set; }
        public string name { get; set; }
        public string descriptionDetails { get; set; }
        public string description { get; set; }
        public Nullable<double> evaluate { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<double> price { get; set; }
        public string color { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment_product> comment_product { get; set; }
        public virtual image_product image_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
        public virtual type_product type_product { get; set; }
    }
}
